"""core commitment control + checkpoints

Revision ID: 40632b1bf6f7
Revises: 
Create Date: 2026-09-02 08:03:02.457290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40632b1bf6f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_person_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_person_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status', native_enum=False, length=32), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type', native_enum=False, length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_deadline'), 'commitments', ['deadline'], unique=False)
    op.create_index(op.f('ix_commitments_direction'), 'commitments', ['direction'], unique=False)
    op.create_index(op.f('ix_commitments_owner_person_id'), 'commitments', ['owner_person_id'], unique=False)
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_index(op.f('ix_commitments_status'), 'commitments', ['status'], unique=False)
    op.create_table('commitment_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='checkpoint_status', native_enum=False, length=32), nullable=False),
    sa.Column('assessment', sa.Enum('UNKNOWN', 'ON_TRACK', 'AT_RISK', 'BLOCKED', name='checkpoint_assessment', native_enum=False, length=32), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'AUTO_RULE', 'AI_SUGGESTED', name='checkpoint_source_type', native_enum=False, length=32), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('assessment_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_checkpoints_commitment_id'), 'commitment_checkpoints', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_checkpoints_scheduled_at'), 'commitment_checkpoints', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_commitment_checkpoints_status'), 'commitment_checkpoints', ['status'], unique=False)
    op.create_table('commitment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'UPDATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'CHECKPOINT_CREATED', 'CHECKPOINT_UPDATED', 'CHECKPOINT_RESCHEDULED', 'CHECKPOINT_COMPLETED', 'CHECKPOINT_SKIPPED', 'CHECKPOINT_ASSESSED_ON_TRACK', 'CHECKPOINT_ASSESSED_AT_RISK', 'CHECKPOINT_ASSESSED_BLOCKED', 'CHECKPOINT_AUTO_RECALCULATED', name='commitment_history_event_type', native_enum=False, length=40), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_history_commitment_id'), 'commitment_history', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_history_created_at'), 'commitment_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitment_history_created_at'), table_name='commitment_history')
    op.drop_index(op.f('ix_commitment_history_commitment_id'), table_name='commitment_history')
    op.drop_table('commitment_history')
    op.drop_index(op.f('ix_commitment_checkpoints_status'), table_name='commitment_checkpoints')
    op.drop_index(op.f('ix_commitment_checkpoints_scheduled_at'), table_name='commitment_checkpoints')
    op.drop_index(op.f('ix_commitment_checkpoints_commitment_id'), table_name='commitment_checkpoints')
    op.drop_table('commitment_checkpoints')
    op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_owner_person_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_direction'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_deadline'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_table('projects')
    op.drop_table('people')
    # ### end Alembic commands ###
