"""initial schema

Revision ID: 8022bd0e9e5b
Revises: 
Create Date: 2026-09-01 12:57:46.365454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8022bd0e9e5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_person_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status'), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'UPDATED', name='commitment_history_event_type'), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitment_history')
    op.drop_table('commitments')
    op.drop_table('projects')
    op.drop_table('people')
    # ### end Alembic commands ###

    # Bug fix (not part of the original autogenerated output): dropping the
    # tables above does not drop the native PostgreSQL ENUM types that
    # backed their columns. Left behind, they collide with the CREATE TYPE
    # statements in upgrade() on a subsequent re-upgrade ("type ... already
    # exists"), which is exactly what broke `alembic downgrade base &&
    # alembic upgrade head` on a clean database. Fixing this here changes
    # only downgrade() — upgrade() and the revision id are untouched, so an
    # already-migrated database stamped at this revision is unaffected.
    op.execute("DROP TYPE IF EXISTS commitment_history_event_type")
    op.execute("DROP TYPE IF EXISTS commitment_source_type")
    op.execute("DROP TYPE IF EXISTS commitment_status")
    op.execute("DROP TYPE IF EXISTS commitment_direction")
