"""add checkpoints, counterparty, portable enums

Revision ID: d18eaa00d57a
Revises: 8022bd0e9e5b
Create Date: 2026-09-02 10:29:21.130531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd18eaa00d57a'
down_revision: Union[str, None] = '8022bd0e9e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitment_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='checkpoint_status', native_enum=False, length=32), nullable=False),
    sa.Column('assessment', sa.Enum('UNKNOWN', 'ON_TRACK', 'AT_RISK', 'BLOCKED', name='checkpoint_assessment', native_enum=False, length=32), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'AUTO_RULE', 'AI_SUGGESTED', name='checkpoint_source_type', native_enum=False, length=32), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('assessment_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_checkpoints_commitment_id'), 'commitment_checkpoints', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_checkpoints_scheduled_at'), 'commitment_checkpoints', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_commitment_checkpoints_status'), 'commitment_checkpoints', ['status'], unique=False)
    op.alter_column('commitment_history', 'event_type',
               existing_type=postgresql.ENUM('CREATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'UPDATED', name='commitment_history_event_type'),
               type_=sa.Enum('CREATED', 'UPDATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'CHECKPOINT_CREATED', 'CHECKPOINT_UPDATED', 'CHECKPOINT_RESCHEDULED', 'CHECKPOINT_COMPLETED', 'CHECKPOINT_SKIPPED', 'CHECKPOINT_ASSESSED_ON_TRACK', 'CHECKPOINT_ASSESSED_AT_RISK', 'CHECKPOINT_ASSESSED_BLOCKED', 'CHECKPOINT_AUTO_RECALCULATED', name='commitment_history_event_type', native_enum=False, length=40),
               existing_nullable=False)
    op.create_index(op.f('ix_commitment_history_commitment_id'), 'commitment_history', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_history_created_at'), 'commitment_history', ['created_at'], unique=False)
    op.add_column('commitments', sa.Column('counterparty_person_id', sa.UUID(), nullable=True))
    op.add_column('commitments', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('commitments', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.alter_column('commitments', 'direction',
               existing_type=postgresql.ENUM('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction'),
               type_=sa.Enum('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('commitments', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status'),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('commitments', 'source_type',
               existing_type=postgresql.ENUM('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type'),
               type_=sa.Enum('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type', native_enum=False, length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_commitments_deadline'), 'commitments', ['deadline'], unique=False)
    op.create_index(op.f('ix_commitments_direction'), 'commitments', ['direction'], unique=False)
    op.create_index(op.f('ix_commitments_owner_person_id'), 'commitments', ['owner_person_id'], unique=False)
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_index(op.f('ix_commitments_status'), 'commitments', ['status'], unique=False)
    op.create_foreign_key(
        'fk_commitments_counterparty_person_id_people',
        'commitments', 'people', ['counterparty_person_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_commitments_counterparty_person_id_people', 'commitments', type_='foreignkey')
    op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_owner_person_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_direction'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_deadline'), table_name='commitments')
    op.alter_column('commitments', 'source_type',
               existing_type=sa.Enum('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type', native_enum=False, length=32),
               type_=postgresql.ENUM('MANUAL', 'MEETING', 'VOICE_NOTE', 'EMAIL', 'CHAT', name='commitment_source_type'),
               existing_nullable=False,
               postgresql_using='source_type::commitment_source_type')
    op.alter_column('commitments', 'status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status', native_enum=False, length=32),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='commitment_status'),
               existing_nullable=False,
               postgresql_using='status::commitment_status')
    op.alter_column('commitments', 'direction',
               existing_type=sa.Enum('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction', native_enum=False, length=32),
               type_=postgresql.ENUM('OWED_TO_ME', 'I_OWE', 'TEAM', name='commitment_direction'),
               existing_nullable=False,
               postgresql_using='direction::commitment_direction')
    op.drop_column('commitments', 'lead_time_days')
    op.drop_column('commitments', 'source_text')
    op.drop_column('commitments', 'counterparty_person_id')
    op.drop_index(op.f('ix_commitment_history_created_at'), table_name='commitment_history')
    op.drop_index(op.f('ix_commitment_history_commitment_id'), table_name='commitment_history')
    # NOTE: this cast fails if any row already has one of the newer
    # CHECKPOINT_* event types (or any future addition) — expected: a
    # downgrade past the point a new event type was actually used cannot
    # preserve rows using values the old enum doesn't have.
    op.alter_column('commitment_history', 'event_type',
               existing_type=sa.Enum('CREATED', 'UPDATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'CHECKPOINT_CREATED', 'CHECKPOINT_UPDATED', 'CHECKPOINT_RESCHEDULED', 'CHECKPOINT_COMPLETED', 'CHECKPOINT_SKIPPED', 'CHECKPOINT_ASSESSED_ON_TRACK', 'CHECKPOINT_ASSESSED_AT_RISK', 'CHECKPOINT_ASSESSED_BLOCKED', 'CHECKPOINT_AUTO_RECALCULATED', name='commitment_history_event_type', native_enum=False, length=40),
               type_=postgresql.ENUM('CREATED', 'DEADLINE_CHANGED', 'COMPLETED', 'CANCELLED', 'UPDATED', name='commitment_history_event_type'),
               existing_nullable=False,
               postgresql_using='event_type::commitment_history_event_type')
    op.drop_index(op.f('ix_commitment_checkpoints_status'), table_name='commitment_checkpoints')
    op.drop_index(op.f('ix_commitment_checkpoints_scheduled_at'), table_name='commitment_checkpoints')
    op.drop_index(op.f('ix_commitment_checkpoints_commitment_id'), table_name='commitment_checkpoints')
    op.drop_table('commitment_checkpoints')
    # ### end Alembic commands ###
